name: Update IPTV List

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 添加写入权限

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests aiohttp tqdm
        
    - name: Run merge script
      run: python scripts/merge_iptv.py
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Commit and push changes
      run: |
        git add txt/merged_file.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update merged IPTV list" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
