name: Update IPTV List

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 添加写入权限

jobs:
  update-iptv:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests>=2.31.0 aiohttp>=3.9.3 tqdm>=4.66.2 pypinyin>=0.50.0 urllib3>=2.2.1 asyncio>=3.4.3
        
    - name: Enable IPv6
      run: |
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
    
    - name: Run merge script
      run: |
        mkdir -p txt
        python scripts/merge_iptv.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add txt/merged_file.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update merged IPTV list" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: merged-iptv
        path: txt/merged_file.txt
        retention-days: 5 
